<?php
/**
 * GLM navigation menu — a replacement for HFE's Navigation Menu widget.
 *
 * WHY THIS EXISTS
 *
 * HFE's nav widget emits 21 selectors reaching specificity (0,6,1), which
 * our design system cannot out-specify without grotesque and brittle
 * selectors. It is effectively a second design system for one component.
 * See docs/nav-menu-replacement.md for the full audit.
 *
 * It also hardcodes 767px and 1024px breakpoints in its JavaScript, while
 * this project breaks at 900px — so between 901px and 1024px the script
 * and the stylesheet disagree about whether to show the hamburger.
 *
 * WHAT IS PRESERVED
 *
 * Everything an editor touches. The menu is still edited at
 * Appearance → Menus, and its tort-category items are still generated by
 * `glm build-pages` from the taxonomy. This replaces rendering only.
 *
 * ACCESSIBILITY
 *
 * Deliberately better than what it replaces:
 *   - real <button> elements, not <div role="button">
 *   - the parent link stays a link; a SEPARATE button toggles the submenu,
 *     avoiding HFE's nested-interactive-element pattern
 *   - focus trap while the mobile menu is open (HFE has none)
 *   - Escape closes and returns focus to the trigger
 *   - full arrow-key navigation
 *
 * @package glm
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Walker producing GLM markup.
 *
 * Kept deliberately small — WordPress already supplies the structural
 * classes (`current-menu-item`, `menu-item-has-children`); we add BEM
 * classes for styling and the submenu toggle button.
 */
class GLM_Nav_Walker extends Walker_Nav_Menu {

	/**
	 * Open a sub-menu level.
	 *
	 * @param string   $output Output buffer.
	 * @param int      $depth  Depth.
	 * @param stdClass $args   Args.
	 */
	public function start_lvl( &$output, $depth = 0, $args = null ) {
		$indent  = str_repeat( "\t", $depth );
		$output .= "\n{$indent}<ul class=\"glm-nav__submenu\">\n";
	}

	/**
	 * Close a sub-menu level.
	 *
	 * @param string   $output Output buffer.
	 * @param int      $depth  Depth.
	 * @param stdClass $args   Args.
	 */
	public function end_lvl( &$output, $depth = 0, $args = null ) {
		$indent  = str_repeat( "\t", $depth );
		$output .= "{$indent}</ul>\n";
	}

	/**
	 * Render one item.
	 *
	 * @param string   $output Output buffer.
	 * @param WP_Post  $item   Menu item.
	 * @param int      $depth  Depth.
	 * @param stdClass $args   Args.
	 * @param int      $id     Current item ID.
	 */
	public function start_el( &$output, $item, $depth = 0, $args = null, $id = 0 ) {

		$classes     = (array) $item->classes;
		$has_children = in_array( 'menu-item-has-children', $classes, true );
		$is_current   = in_array( 'current-menu-item', $classes, true )
			|| in_array( 'current-menu-ancestor', $classes, true );

		$li_classes = array( 'glm-nav__item' );
		if ( $has_children ) {
			$li_classes[] = 'glm-nav__item--has-children';
		}
		if ( $is_current ) {
			$li_classes[] = 'is-current';
		}
		if ( $depth > 0 ) {
			$li_classes[] = 'glm-nav__item--child';
		}

		$output .= sprintf(
			'<li class="%s">',
			esc_attr( implode( ' ', $li_classes ) )
		);

		$link_class = $depth > 0 ? 'glm-nav__link glm-nav__link--child' : 'glm-nav__link';

		$output .= sprintf(
			'<a class="%s" href="%s"%s%s>%s</a>',
			esc_attr( $link_class ),
			esc_url( $item->url ? $item->url : '#' ),
			$item->target ? ' target="' . esc_attr( $item->target ) . '"' : '',
			$is_current ? ' aria-current="page"' : '',
			esc_html( $item->title )
		);

		/*
		 * A separate toggle button, sibling to the link.
		 *
		 * HFE wraps the parent link inside <div role="button">, which nests
		 * one interactive element inside another — screen readers announce
		 * it inconsistently and the link becomes hard to activate. Keeping
		 * them as siblings means the link navigates and the button expands,
		 * each doing exactly one thing.
		 */
		if ( $has_children ) {
			$output .= sprintf(
				'<button type="button" class="glm-nav__toggle-sub" aria-expanded="false" aria-haspopup="true">'
					. '<span class="screen-reader-text">%s</span>'
					. '<span class="glm-nav__caret" aria-hidden="true"></span>'
				. '</button>',
				/* translators: %s: parent menu item name. */
				esc_html( sprintf( __( 'Show submenu for %s', 'glm' ), $item->title ) )
			);
		}
	}

	/**
	 * Close an item.
	 *
	 * @param string   $output Output buffer.
	 * @param WP_Post  $item   Menu item.
	 * @param int      $depth  Depth.
	 * @param stdClass $args   Args.
	 */
	public function end_el( &$output, $item, $depth = 0, $args = null ) {
		$output .= "</li>\n";
	}
}

/**
 * Render the primary navigation.
 *
 * @param array $args Optional overrides.
 * @return string
 */
function glm_render_nav( array $args = array() ) {

	$args = wp_parse_args(
		$args,
		array(
			'menu'       => 'Primary',
			'aria_label' => __( 'Primary', 'glm' ),
			'toggle_label' => __( 'Menu', 'glm' ),
		)
	);

	if ( ! wp_get_nav_menu_object( $args['menu'] ) ) {
		if ( current_user_can( 'edit_theme_options' ) ) {
			return '<p style="padding:1rem;border:2px dashed #b91c1c;color:#b91c1c;">'
				. 'Menu <code>' . esc_html( $args['menu'] ) . '</code> not found. '
				. 'Run <code>wp glm build-pages</code> or create it at Appearance → Menus.</p>';
		}
		return '';
	}

	$items = wp_nav_menu(
		array(
			'menu'        => $args['menu'],
			'container'   => false,
			'items_wrap'  => '<ul id="%1$s" class="%2$s">%3$s</ul>',
			'menu_id'     => 'glm-nav-menu',
			'menu_class'  => 'glm-nav__list',
			'walker'      => new GLM_Nav_Walker(),
			'fallback_cb' => false,
			'echo'        => false,
			'depth'       => 2,
		)
	);

	if ( ! $items ) {
		return '';
	}

	ob_start();
	?>
	<nav class="glm-nav" aria-label="<?php echo esc_attr( $args['aria_label'] ); ?>" data-glm-nav>
		<button
			type="button"
			class="glm-nav__toggle"
			aria-expanded="false"
			aria-controls="glm-nav-menu"
		>
			<span class="screen-reader-text"><?php echo esc_html( $args['toggle_label'] ); ?></span>
			<span class="glm-nav__burger" aria-hidden="true">
				<span></span><span></span><span></span>
			</span>
		</button>
		<?php echo $items; // phpcs:ignore WordPress.Security.EscapingOutput — walker escapes. ?>
	</nav>
	<?php
	return ob_get_clean();
}

/**
 * [glm_nav] — insert the navigation.
 *
 * @param array $atts Attributes.
 * @return string
 */
function glm_nav_shortcode( $atts ) {

	$atts = shortcode_atts(
		array(
			'menu'  => 'Primary',
			'label' => __( 'Primary', 'glm' ),
		),
		$atts,
		'glm_nav'
	);

	return glm_render_nav(
		array(
			'menu'       => $atts['menu'],
			'aria_label' => $atts['label'],
		)
	);
}
add_shortcode( 'glm_nav', 'glm_nav_shortcode' );

/**
 * Enqueue the navigation script only when it is used.
 *
 * Registered rather than enqueued up front; the shortcode and the header
 * template both call glm_enqueue_nav() so a page without navigation does
 * not carry the asset.
 */
function glm_register_nav_assets() {
	wp_register_script(
		'glm-nav',
		GLM_URI . '/assets/js/nav.js',
		array(),
		glm_asset_version( '/assets/js/nav.js' ),
		true
	);
}
add_action( 'wp_enqueue_scripts', 'glm_register_nav_assets' );

/**
 * Ensure the nav script is on the page.
 */
function glm_enqueue_nav() {
	if ( ! wp_script_is( 'glm-nav', 'enqueued' ) ) {
		wp_enqueue_script( 'glm-nav' );
	}
}
add_action( 'wp_enqueue_scripts', 'glm_enqueue_nav', 20 );

/**
 * Drop HFE's widget stylesheets.
 *
 * HFE enqueues these UNCONDITIONALLY for every page, whether or not any
 * of its widgets are present. Since the navigation menu was the last HFE
 * widget in use and it has been replaced, all of it is dead weight:
 *
 *   hfe-widgets-style                    83,015 bytes
 *   hfe-social-share-icons-fontawesome   72,184
 *   hfe-elementor-icons                  22,258
 *   hfe-icons-list                       10,255
 *   hfe-social-icons                      5,110
 *   hfe-social-share-icons-brands           732
 *   hfe-nav-menu-icons                      727
 *   ------------------------------------------
 *                                       194,281 bytes
 *
 * `hfe-style` is deliberately KEPT — it is the header/footer template
 * layout CSS, which we still rely on (R6).
 *
 * GOTCHA: if an HFE widget is ever added to a template, its styling will
 * be missing. `wp glm audit` fails in that case rather than leaving it to
 * be discovered visually. To re-enable, return false from the filter.
 */
function glm_dequeue_hfe_widget_assets() {

	/**
	 * Whether to drop HFE's unconditional widget stylesheets.
	 *
	 * @param bool $drop Default true.
	 */
	if ( ! apply_filters( 'glm_dequeue_hfe_assets', true ) ) {
		return;
	}

	foreach ( glm_hfe_widget_handles() as $handle ) {
		wp_dequeue_style( $handle );
		wp_deregister_style( $handle );
	}
}

/*
 * Hooked to wp_print_styles, not wp_enqueue_scripts.
 *
 * HFE enqueues on `elementor/frontend/after_register_scripts`, which fires
 * after wp_enqueue_scripts has finished — so dequeuing there ran too early
 * and had no effect. wp_print_styles is the last point before output.
 */
add_action( 'wp_print_styles', 'glm_dequeue_hfe_widget_assets', 100 );

/**
 * The HFE stylesheet handles we drop.
 *
 * Shared with the audit so the two cannot disagree.
 *
 * @return string[]
 */
function glm_hfe_widget_handles() {
	return array(
		'hfe-widgets-style',
		'hfe-elementor-icons',
		'hfe-icons-list',
		'hfe-social-icons',
		'hfe-social-share-icons-brands',
		'hfe-social-share-icons-fontawesome',
		'hfe-nav-menu-icons',
	);
}
